export {default as Leagues} from './Leagues'
export {default as Standings} from './Standings'
export {default as Club} from './Club'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Reset} from './Reset'
export {default as Home} from './Home'